# Generated by Django 5.1.1 on 2024-09-14 11:40

import django.utils.timezone
import mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_attempt', models.DateTimeField(auto_now_add=True, verbose_name='attempt_time')),
                ('attempt_status', models.CharField(choices=[('successful', 'attempt_successful'), ('failed', 'attempt_failed')], max_length=100, verbose_name='attempt_status')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='server_response')),
            ],
            options={
                'verbose_name': 'attempt',
                'verbose_name_plural': 'attempts',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='client_name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='client_surname')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'permissions': [('can_view_email', 'Can view email')],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_sent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='send_timestamp')),
                ('mailing_end', models.DateTimeField(default=mailing.models.one_week_from_now, verbose_name='end_timestamp')),
                ('mailing_periodicity', models.CharField(choices=[('one time', 'once'), ('day', 'daily'), ('week', 'weekly'), ('month', 'monthly')], max_length=100, verbose_name='periodicity')),
                ('mailing_status', models.CharField(choices=[('created', 'mailing_created'), ('started', 'mailing_started'), ('completed', 'mailing_complete')], max_length=100, verbose_name='status')),
            ],
            options={
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailings',
                'permissions': [('can_edit_mailing_status', 'Can edit mailing status')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='message_subject')),
                ('text', models.TextField(blank=True, null=True, verbose_name='message_text')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
    ]
